# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Check and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x, 22.x, 24.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --save-dev
      - name: Build
        run: npm run build
      - name: Run tests
        run: npx ng test --browsers ChromeHeadless --watch false

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    environment:
      name: ${{ inputs.environment }}
      url: ${{ needs.select-environment.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: 'cd "${{ vars.PROJECT_LOCATION }}" && ./.scripts/deploy.sh'
